// <auto-generated />
using System;
using AgendaMedicaMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgendaMedicaMvc.Migrations
{
    [DbContext(typeof(AgendaMedicaMvcContext))]
    [Migration("20220712234940_CorrigindoDateFormat")]
    partial class CorrigindoDateFormat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AgendaMedicaMvc.Models.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("MedicoId");

                    b.Property<int>("PacienteId");

                    b.HasKey("Id");

                    b.ToTable("Agenda");
                });

            modelBuilder.Entity("AgendaMedicaMvc.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AgendaId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Specialization");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("AgendaMedicaMvc.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AgendaId");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<int>("Phone");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("AgendaMedicaMvc.Models.Medico", b =>
                {
                    b.HasOne("AgendaMedicaMvc.Models.Agenda")
                        .WithMany("Medico")
                        .HasForeignKey("AgendaId");
                });

            modelBuilder.Entity("AgendaMedicaMvc.Models.Paciente", b =>
                {
                    b.HasOne("AgendaMedicaMvc.Models.Agenda")
                        .WithMany("Paciente")
                        .HasForeignKey("AgendaId");
                });
#pragma warning restore 612, 618
        }
    }
}
